[theme]
base = "dark"
primaryColor = "#3b82f6"
backgroundColor = "#040810"
secondaryBackgroundColor = "#070d1c"
textColor = "#e2e8f0"
font = "sans serif"

[server]
headless = true
enableXsrfProtection = true
enableCORS = false
maxUploadSize = 5

[browser]
gatherUsageStats = false
